/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as OwnerRouteImport } from './routes/_owner'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OwnerShareLinksRouteImport } from './routes/_owner.share-links'
import { Route as OwnerSearchRouteImport } from './routes/_owner.search'
import { Route as OwnerSalesmenRouteImport } from './routes/_owner.salesmen'
import { Route as OwnerProductsRouteImport } from './routes/_owner.products'
import { Route as OwnerOrdersRouteImport } from './routes/_owner.orders'
import { Route as OwnerMakeOrdersRouteImport } from './routes/_owner.make-orders'
import { Route as OwnerDashboardRouteImport } from './routes/_owner.dashboard'
import { Route as OwnerCustomersRouteImport } from './routes/_owner.customers'
import { Route as OwnerCompaniesRouteImport } from './routes/_owner.companies'
import { Route as OwnerCategoriesRouteImport } from './routes/_owner.categories'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)

const OwnerRoute = OwnerRouteImport.update({
  id: '/_owner',
  getParentRoute: () => rootRouteImport,
} as any)

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

const OwnerShareLinksRoute = OwnerShareLinksRouteImport.update({
  id: '/share-links',
  path: '/share-links',
  getParentRoute: () => OwnerRoute,
} as any)

const OwnerSearchRoute = OwnerSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => OwnerRoute,
} as any)

const OwnerSalesmenRoute = OwnerSalesmenRouteImport.update({
  id: '/salesmen',
  path: '/salesmen',
  getParentRoute: () => OwnerRoute,
} as any)

const OwnerProductsRoute = OwnerProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => OwnerRoute,
} as any)

const OwnerOrdersRoute = OwnerOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => OwnerRoute,
} as any)

const OwnerMakeOrdersRoute = OwnerMakeOrdersRouteImport.update({
  id: '/make-orders',
  path: '/make-orders',
  getParentRoute: () => OwnerRoute,
} as any)

const OwnerDashboardRoute = OwnerDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => OwnerRoute,
} as any)

const OwnerCustomersRoute = OwnerCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => OwnerRoute,
} as any)

const OwnerCompaniesRoute = OwnerCompaniesRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => OwnerRoute,
} as any)

const OwnerCategoriesRoute = OwnerCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => OwnerRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/categories': typeof OwnerCategoriesRoute
  '/companies': typeof OwnerCompaniesRoute
  '/customers': typeof OwnerCustomersRoute
  '/dashboard': typeof OwnerDashboardRoute
  '/make-orders': typeof OwnerMakeOrdersRoute
  '/orders': typeof OwnerOrdersRoute
  '/products': typeof OwnerProductsRoute
  '/salesmen': typeof OwnerSalesmenRoute
  '/search': typeof OwnerSearchRoute
  '/share-links': typeof OwnerShareLinksRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/categories': typeof OwnerCategoriesRoute
  '/companies': typeof OwnerCompaniesRoute
  '/customers': typeof OwnerCustomersRoute
  '/dashboard': typeof OwnerDashboardRoute
  '/make-orders': typeof OwnerMakeOrdersRoute
  '/orders': typeof OwnerOrdersRoute
  '/products': typeof OwnerProductsRoute
  '/salesmen': typeof OwnerSalesmenRoute
  '/search': typeof OwnerSearchRoute
  '/share-links': typeof OwnerShareLinksRoute
}

export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_owner': typeof OwnerRouteWithChildren
  '/auth': typeof AuthRoute
  '/_owner/categories': typeof OwnerCategoriesRoute
  '/_owner/companies': typeof OwnerCompaniesRoute
  '/_owner/customers': typeof OwnerCustomersRoute
  '/_owner/dashboard': typeof OwnerDashboardRoute
  '/_owner/make-orders': typeof OwnerMakeOrdersRoute
  '/_owner/orders': typeof OwnerOrdersRoute
  '/_owner/products': typeof OwnerProductsRoute
  '/_owner/salesmen': typeof OwnerSalesmenRoute
  '/_owner/search': typeof OwnerSearchRoute
  '/_owner/share-links': typeof OwnerShareLinksRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/categories'
    | '/companies'
    | '/customers'
    | '/dashboard'
    | '/make-orders'
    | '/orders'
    | '/products'
    | '/salesmen'
    | '/search'
    | '/share-links'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/categories'
    | '/companies'
    | '/customers'
    | '/dashboard'
    | '/make-orders'
    | '/orders'
    | '/products'
    | '/salesmen'
    | '/search'
    | '/share-links'
  id:
    | '__root__'
    | '/'
    | '/_owner'
    | '/auth'
    | '/_owner/categories'
    | '/_owner/companies'
    | '/_owner/customers'
    | '/_owner/dashboard'
    | '/_owner/make-orders'
    | '/_owner/orders'
    | '/_owner/products'
    | '/_owner/salesmen'
    | '/_owner/search'
    | '/_owner/share-links'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OwnerRoute: typeof OwnerRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_owner': {
      id: '/_owner'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof OwnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_owner/share-links': {
      id: '/_owner/share-links'
      path: '/share-links'
      fullPath: '/share-links'
      preLoaderRoute: typeof OwnerShareLinksRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/_owner/search': {
      id: '/_owner/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof OwnerSearchRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/_owner/salesmen': {
      id: '/_owner/salesmen'
      path: '/salesmen'
      fullPath: '/salesmen'
      preLoaderRoute: typeof OwnerSalesmenRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/_owner/products': {
      id: '/_owner/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof OwnerProductsRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/_owner/orders': {
      id: '/_owner/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OwnerOrdersRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/_owner/make-orders': {
      id: '/_owner/make-orders'
      path: '/make-orders'
      fullPath: '/make-orders'
      preLoaderRoute: typeof OwnerMakeOrdersRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/_owner/dashboard': {
      id: '/_owner/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof OwnerDashboardRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/_owner/customers': {
      id: '/_owner/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof OwnerCustomersRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/_owner/companies': {
      id: '/_owner/companies'
      path: '/companies'
      fullPath: '/companies'
      preLoaderRoute: typeof OwnerCompaniesRouteImport
      parentRoute: typeof OwnerRoute
    }
    '/_owner/categories': {
      id: '/_owner/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof OwnerCategoriesRouteImport
      parentRoute: typeof OwnerRoute
    }
  }
}

interface OwnerRouteChildren {
  OwnerCategoriesRoute: typeof OwnerCategoriesRoute
  OwnerCompaniesRoute: typeof OwnerCompaniesRoute
  OwnerCustomersRoute: typeof OwnerCustomersRoute
  OwnerDashboardRoute: typeof OwnerDashboardRoute
  OwnerMakeOrdersRoute: typeof OwnerMakeOrdersRoute
  OwnerOrdersRoute: typeof OwnerOrdersRoute
  OwnerProductsRoute: typeof OwnerProductsRoute
  OwnerSalesmenRoute: typeof OwnerSalesmenRoute
  OwnerSearchRoute: typeof OwnerSearchRoute
  OwnerShareLinksRoute: typeof OwnerShareLinksRoute
}

const OwnerRouteChildren: OwnerRouteChildren = {
  OwnerCategoriesRoute: OwnerCategoriesRoute,
  OwnerCompaniesRoute: OwnerCompaniesRoute,
  OwnerCustomersRoute: OwnerCustomersRoute,
  OwnerDashboardRoute: OwnerDashboardRoute,
  OwnerMakeOrdersRoute: OwnerMakeOrdersRoute,
  OwnerOrdersRoute: OwnerOrdersRoute,
  OwnerProductsRoute: OwnerProductsRoute,
  OwnerSalesmenRoute: OwnerSalesmenRoute,
  OwnerSearchRoute: OwnerSearchRoute,
  OwnerShareLinksRoute: OwnerShareLinksRoute,
}

const OwnerRouteWithChildren = OwnerRoute._addFileChildren(OwnerRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OwnerRoute: OwnerRouteWithChildren,
  AuthRoute: AuthRoute,
}

export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
