/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as SalesmanRouteImport } from './routes/_salesman'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SalesmanOrdersRouteImport } from './routes/_salesman.orders'
import { Route as SalesmanCartRouteImport } from './routes/_salesman.cart'
import { Route as SalesmanBrowseRouteImport } from './routes/_salesman.browse'
import { Route as SalesmanProductIdRouteImport } from './routes/_salesman.product.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesmanRoute = SalesmanRouteImport.update({
  id: '/_salesman',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesmanOrdersRoute = SalesmanOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => SalesmanRoute,
} as any)
const SalesmanCartRoute = SalesmanCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => SalesmanRoute,
} as any)
const SalesmanBrowseRoute = SalesmanBrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => SalesmanRoute,
} as any)
const SalesmanProductIdRoute = SalesmanProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => SalesmanRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/browse': typeof SalesmanBrowseRoute
  '/cart': typeof SalesmanCartRoute
  '/orders': typeof SalesmanOrdersRoute
  '/product/$id': typeof SalesmanProductIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/browse': typeof SalesmanBrowseRoute
  '/cart': typeof SalesmanCartRoute
  '/orders': typeof SalesmanOrdersRoute
  '/product/$id': typeof SalesmanProductIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_salesman': typeof SalesmanRouteWithChildren
  '/auth': typeof AuthRoute
  '/_salesman/browse': typeof SalesmanBrowseRoute
  '/_salesman/cart': typeof SalesmanCartRoute
  '/_salesman/orders': typeof SalesmanOrdersRoute
  '/_salesman/product/$id': typeof SalesmanProductIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auth' | '/browse' | '/cart' | '/orders' | '/product/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/browse' | '/cart' | '/orders' | '/product/$id'
  id:
    | '__root__'
    | '/'
    | '/_salesman'
    | '/auth'
    | '/_salesman/browse'
    | '/_salesman/cart'
    | '/_salesman/orders'
    | '/_salesman/product/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SalesmanRoute: typeof SalesmanRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_salesman': {
      id: '/_salesman'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SalesmanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_salesman/orders': {
      id: '/_salesman/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof SalesmanOrdersRouteImport
      parentRoute: typeof SalesmanRoute
    }
    '/_salesman/cart': {
      id: '/_salesman/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof SalesmanCartRouteImport
      parentRoute: typeof SalesmanRoute
    }
    '/_salesman/browse': {
      id: '/_salesman/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof SalesmanBrowseRouteImport
      parentRoute: typeof SalesmanRoute
    }
    '/_salesman/product/$id': {
      id: '/_salesman/product/$id'
      path: '/product/$id'
      fullPath: '/product/$id'
      preLoaderRoute: typeof SalesmanProductIdRouteImport
      parentRoute: typeof SalesmanRoute
    }
  }
}

interface SalesmanRouteChildren {
  SalesmanBrowseRoute: typeof SalesmanBrowseRoute
  SalesmanCartRoute: typeof SalesmanCartRoute
  SalesmanOrdersRoute: typeof SalesmanOrdersRoute
  SalesmanProductIdRoute: typeof SalesmanProductIdRoute
}

const SalesmanRouteChildren: SalesmanRouteChildren = {
  SalesmanBrowseRoute: SalesmanBrowseRoute,
  SalesmanCartRoute: SalesmanCartRoute,
  SalesmanOrdersRoute: SalesmanOrdersRoute,
  SalesmanProductIdRoute: SalesmanProductIdRoute,
}

const SalesmanRouteWithChildren = SalesmanRoute._addFileChildren(
  SalesmanRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SalesmanRoute: SalesmanRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
